### ISSUE TITLE
Wheezy: No package matching 'nodejs' is available

### ISSUE THREAD

**Issue by oloc** [resmo/ansible-role-dashing#2]
The nodejs package is not available in wheezy.

Maybe you should add something like that:
```
  - name: Ensure wheezy-backport is added.
    lineinfile:
      dest: "/etc/apt/sources.list.d/wheezy-backports.list"
      line: "deb http://ftp.debian.org/debian wheezy-backports main"
      state: present
    when: ansible_distribution_release | lower  == 'wheezy'
```

Source: https://packages.debian.org/search?keywords=nodejs
